modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module
      app_name: SimApp
      begin_blockers: [ staking, swap ]
      end_blockers: [ staking ]
      init_genesis: [ auth, bank, staking, genutil, swap ]
      override_store_keys:
        - module_name: auth
          kv_store_key: acc
  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: noble
      module_account_permissions:
        - account: fee_collector
        - account: bonded_tokens_pool
          permissions: [ burner, staking ]
        - account: not_bonded_tokens_pool
          permissions: [ burner, staking ]
  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module
      blocked_module_accounts_override:
        [ bonded_tokens_pool, not_bonded_tokens_pool ]
  - name: consensus
    config:
      "@type": cosmos.consensus.module.v1.Module
  - name: genutil
    config:
      "@type": cosmos.genutil.module.v1.Module
  - name: staking
    config:
      "@type": cosmos.staking.module.v1.Module
  - name: tx
    config:
      "@type": cosmos.tx.config.v1.Config

  - name: swap
    config:
      "@type": noble.swap.module.v1.Module
      # NOTE: This is a dummy account used for local testing.
      # occur subway woman achieve deputy rapid museum point usual appear oil blue rate title claw debate flag gallery level object baby winner erase carbon
      authority: noble1zw7vatnx0vla7gzxucgypz0kfr6965akpvzw69
      base_denom: uusdn
      base_minimum_deposit: 1e6
      max_add_liquidity_slippage_percentage: 0.5e4 # 0.5% slippage
      stableswap:
        unbonding_block_delta: 1
        max_spread_allowed: 150 # 1.5% spread
